name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: npm test
      run: |
        npm i
        npm test
